### ISSUE TITLE
배포버전을 만들어라

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora-deposit-cli#28]
가장 마직막을 배포판은 [agora_v0.0.2](https://github.com/bosagora/agora-deposit-cli/releases/tag/agora_v0.0.2)
입니다.
새로운 배포판을 생성해 주세요

**Comment by Kang-Simon** [comment]
1839d2f 버전으로 v0.0.3 릴리즈 생성완료했습니다
https://github.com/bosagora/agora-deposit-cli/releases/tag/agora_v0.0.3
